# Generated by Django 4.1.8 on 2024-04-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soleodetails',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='card/'),
        ),
        migrations.AddField(
            model_name='soleodetails',
            name='ssn_card',
            field=models.ImageField(blank=True, null=True, upload_to='sncard/'),
        ),
    ]
